### ISSUE TITLE
Issue when waking machine from sleep

### ISSUE THREAD

**Issue by bdwilson** [godenzim/readernotifier#3]
Hi, I've noticed an issue that is still prevalent in 2.2.3 where if I put my laptop to sleep, then wake it up, I get a prompt from Reader Notifier about unable to connect to google and the exclamation icon displays on reader notifier.  It does this each time I wake the machine from sleep.  Just wondering if there was a way to suppress this warning if the machine is waking or perhaps suppress all warnings (only show a warning if creds don't work, don't tell me that you can't connect to google).   Also, the exclamation icon stays that way even if connectivity is restored (wireless finishes coming up), but does go away if there are new items.

Thanks again for your work on this!  I'm so glad that someone resurrected it!

Brian

**Comment by godenzim** [comment]
I will address this issue in the next update. Thank you for your input.

**Comment by bdwilson** [comment]
Any updates on this one?   Sorry for bugging ya :)

**Comment by bdwilson** [comment]
I fixed it in my fork.   Commented out 2 lines; not sure if that's the best way to go about it, but it's not nagging me now :)

**Comment by ghazel** [comment]
This is still an issue since there has not been a release which fixes it. It looks this is the fix bdwilson mentioned:

https://github.com/bdwilson/readernotifier/commit/46c91c0c3a225ddc13a9e56c17d5bb19533c8b0c
